/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiMentorRouteImport } from './routes/ai-mentor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StartupRouteImport } from './routes/startup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMentorRoute = AiMentorRouteImport.update({
  id: '/ai-mentor',
  path: '/ai-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupRoute = StartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-mentor': typeof AiMentorRoute
  '/dashboard': typeof DashboardRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startup': typeof StartupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-mentor': typeof AiMentorRoute
  '/dashboard': typeof DashboardRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startup': typeof StartupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-mentor': typeof AiMentorRoute
  '/dashboard': typeof DashboardRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startup': typeof StartupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-mentor'
    | '/dashboard'
    | '/learning'
    | '/login'
    | '/mentors'
    | '/notifications'
    | '/projects'
    | '/sitemap.xml'
    | '/startup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-mentor'
    | '/dashboard'
    | '/learning'
    | '/login'
    | '/mentors'
    | '/notifications'
    | '/projects'
    | '/sitemap.xml'
    | '/startup'
  id:
    | '__root__'
    | '/'
    | '/ai-mentor'
    | '/dashboard'
    | '/learning'
    | '/login'
    | '/mentors'
    | '/notifications'
    | '/projects'
    | '/sitemap.xml'
    | '/startup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiMentorRoute: typeof AiMentorRoute
  DashboardRoute: typeof DashboardRoute
  LearningRoute: typeof LearningRoute
  LoginRoute: typeof LoginRoute
  MentorsRoute: typeof MentorsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartupRoute: typeof StartupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-mentor': {
      id: '/ai-mentor'
      path: '/ai-mentor'
      fullPath: '/ai-mentor'
      preLoaderRoute: typeof AiMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup': {
      id: '/startup'
      path: '/startup'
      fullPath: '/startup'
      preLoaderRoute: typeof StartupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiMentorRoute: AiMentorRoute,
  DashboardRoute: DashboardRoute,
  LearningRoute: LearningRoute,
  LoginRoute: LoginRoute,
  MentorsRoute: MentorsRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartupRoute: StartupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
